services:
  postgres:
    image: postgres:18-alpine3.23
    environment:
      POSTGRES_USER: runguard
      POSTGRES_PASSWORD: runguard
      POSTGRES_DB: runguard
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U runguard"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine3.23
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.14.0-alpine3.22
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--jetstream -m 8222"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: