global:
  environment: dev
  imageTag: v0.1.0

api-gateway:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

backend:
  replicaCount: 1

operator:
  replicaCount: 1

reasoner:
  replicaCount: 1

worker:
  replicaCount: 1

web-ui:
  replicaCount: 1
