global:
  environment: dev
  imageTag: latest

api-gateway:
  fullnameOverride: api-gateway
  replicaCount: 1
  autoscaling:
    enabled: false
  image:
    repository: runguard-api-gateway
    tag: latest
    pullPolicy: Never
  env:
    - name: API_GATEWAY_PORT
      value: "8080"
    - name: BACKEND_URL
      value: "http://backend:8081"
    - name: OTEL_SDK_DISABLED
      value: "true"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

backend:
  fullnameOverride: backend
  replicaCount: 1
  image:
    repository: runguard-backend
    tag: latest
    pullPolicy: Never

operator:
  fullnameOverride: operator
  replicaCount: 1
  image:
    repository: runguard-operator
    tag: latest
    pullPolicy: Never

reasoner:
  fullnameOverride: reasoner
  replicaCount: 1
  image:
    repository: runguard-reasoner
    tag: latest
    pullPolicy: Never

worker:
  fullnameOverride: worker
  replicaCount: 1
  image:
    repository: runguard-worker
    tag: latest
    pullPolicy: Never
  env:
    - name: NATS_URL
      value: "nats://nats:4222"
    - name: BACKEND_URL
      value: "http://backend:8081"
    - name: OTEL_SDK_DISABLED
      value: "true"

web-ui:
  fullnameOverride: web-ui
  replicaCount: 1
  image:
    repository: runguard-web-ui
    tag: latest
    pullPolicy: Never
