replicaCount: 1

image:
  repository: ghcr.io/phuoctmse/runguard/web-ui
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101

# nginx needs to write temp files — no readOnlyRootFilesystem
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 80

httpRoute:
  enabled: true
  annotations: {}
  parentRefs:
    - name: runguard-gateway
      sectionName: https
  hostnames:
    - runguard.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

env: []
envFrom: []

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
