---
# dev + staging: automated sync
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: runguard-auto
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            branch: v2
          - env: staging
            branch: main
  template:
    metadata:
      name: "runguard-{{env}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/phuoctmse/runguard.git
        targetRevision: "{{branch}}"
        path: infra/runguard
        helm:
          valueFiles:
            - values.yaml
            - "values-{{env}}.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "runguard-{{env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
---
# prod: manual sync only
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: runguard-prod
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: prod
            branch: main
  template:
    metadata:
      name: "runguard-{{env}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/phuoctmse/runguard.git
        targetRevision: "{{branch}}"
        path: infra/runguard
        helm:
          valueFiles:
            - values.yaml
            - "values-{{env}}.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "runguard-{{env}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
