---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runguard-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/phuoctmse/runguard.git
    targetRevision: v2
    path: infra/runguard
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: runguard-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runguard-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/phuoctmse/runguard.git
    targetRevision: main
    path: infra/runguard
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: runguard-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runguard-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/phuoctmse/runguard.git
    targetRevision: main
    path: infra/runguard
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: runguard-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
